name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    strategy:
      matrix:
        version: [mainline, stable]

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file ${{ matrix.version }}/Dockerfile --tag my-image-name:$(date +%s)
